# ==========================
# Programs
# ==========================

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = dolphin
$menu = pkill wofi || wofi --show drun --style ~/.config/wofi/style.css
